# Site wide configuration
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
title:            ADAN CONDORI
locale:           en_US
#url:              http://localhost:4000
url:              https://adancondori.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Adan Condori C.
  avatar: perfil-cv.jpeg
  bio: "Computer Engineer<br/> <a href=\"https://adancondori.github.io\">Web Page</a>"
  email: adan.condoric@gmail.com
  disqus-shortname: acondori
  twitter: AdanCondori
  facebook: adan.condoric
  google:
    plus: AdanCondoriC
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: adancondori
  stackoverflow: #9122/adancondori
  linkedin: adancondori
  hackernews: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  scholar: adancondori
  llnl: #gamblin2


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
